
- name: Mettre à jour les paquets
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"


- name: Mettre à jour les paquets
  dnf:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == "RedHat"


- name: Installer Git
  apt:
    name: git
    state: present
  when: ansible_facts['os_family'] == "Debian"


- name: Installer Git
  dnf:
    name: git
    state: present
  when: ansible_facts['os_family'] == "RedHat"


- name: Télécharger le script d'installation Node.js
  get_url:
    url: https://rpm.nodesource.com/setup_23.x
    dest: /tmp/setup_node.sh
    mode: '0755'
  when: ansible_facts['os_family'] == "RedHat"


- name: Exécuter le script Node.js
  command: bash /tmp/setup_node.sh
  when: ansible_facts['os_family'] == "RedHat"


- name: Installer Node.js
  dnf:
    name: nodejs
    state: present
  when: ansible_facts['os_family'] == "RedHat"


- name: Installer Node.js et npm
  apt:
    name:
      - nodejs
      - npm
    state: present
  when: ansible_facts['os_family'] == "Debian"


- name: Cloner le dépôt Git dans /opt/quiz-ansible
  git:
    repo: https://github.com/franklin-tutorials/quiz-ansible.git
    dest: /opt/quiz-ansible
    force: yes


- name: Installer les dépendances npm install
  npm:
    path: /opt/quiz-ansible
    state: present


- name: Compiler l'app avec npm run build
  command: npm run build
  args:
    chdir: /opt/quiz-ansible


- name: Installer serve en global avec le module npm
  npm:
    name: serve
    global: yes
    state: present


- name: Lancer l'app en tâche de fond avec shell
  shell: nohup serve -s dist &
  args:
    chdir: /opt/quiz-ansible
  async: 3600
  poll: 0
